### ISSUE TITLE
per disc numbering in multidisc release

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#10]
http://beets.readthedocs.org/en/latest/reference/config.html#per-disc-numbering

wanted!

we set `per_disc_numbering: yes` and add

```
paths:
    default: $albumartist/$album%aunique{}/$disc-$track $title
```

?

**Comment by Schweinepriester** [comment]
absolutely!

the paths need customizing anyway in general

**Comment by Schweinepriester** [comment]
see also http://beets.readthedocs.org/en/latest/reference/pathformat.html

**Comment by zabelhaft** [comment]
as well as here: http://beets.readthedocs.org/en/latest/reference/config.html#path-format-configuration

**Comment by zabelhaft** [comment]
http://beets.readthedocs.org/en/latest/faq.html#create-disc-n-directories-for-multi-disc-albums
this could help
