### ISSUE TITLE
"missing" plugin

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#13]
http://beets.readthedocs.org/en/latest/plugins/missing.html

import plugin and define a string to check importet albums?

**Comment by Schweinepriester** [comment]
Just tested a little bit with Alcest - Shelter: Removed one track from the folder, started import:

```
Tagging:
    Alcest - Shelter
URL:
    http://musicbrainz.org/release/33665cd0-e1d9-41a2-b2ad-6f539f562a2c
(Similarity: 95.8%) (missing tracks, tracks) (Vinyl, 2014, DE, Prophecy Productions, Copper vinyl)
 * La nuit marce avec moi -> La nuit marche avec moi (title)
 * Voix Sereines          -> Voix sereines
 * L'Eveil des muses      -> L'éveil des muses
Missing tracks (1/8 - 12.5%):
 ! Délivrance (#8) (10:05)
```

beets already checks for missing tracks even before the import, which was your intention?
=> close?

or do we still want to implement the "missing" plugin? which of course is fine
=> should be easy

**Comment by Schweinepriester** [comment]
Closing, since beets checks missing stuff on import.
