### ISSUE TITLE
"discogs" plugin

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#14]
http://beets.readthedocs.org/en/latest/plugins/discogs.html

this may enhance the autotag feature for false detected albums.

**Comment by Schweinepriester** [comment]
+1

also: the Acoustid plugin etc.

**Comment by zabelhaft** [comment]
although the acoustid plugin only uses another technique to access the
musicbrainz db, it is allready in the issue with features for 0.0.2
