### ISSUE TITLE
sort_album for beet ls -a

### ISSUE THREAD

**Issue by Schweinepriester** [Schweinepriester/beets-config#21]
while you can specify the order [manually](http://beets.readthedocs.org/en/v1.3.13/reference/query.html#sort-order) like e.g. this:

```
beet ls -a 'added:2015-06-27' added-
```

i'd like to suggest, that we configure [`sort_album`](http://beets.readthedocs.org/en/v1.3.13/reference/config.html#sort-album) to `added- albumartist+ album+` to produce the order we usually have

for reference: [all default fields](https://beets.readthedocs.org/en/v1.3.13/reference/pathformat.html#available-values)

**Comment by zabelhaft** [comment]
isn't `added- albumartist+ album+` the default setting?

**Comment by Schweinepriester** [comment]
nope

> Defaults to `albumartist+ album+`

(without the `added-` in front)

**Comment by zabelhaft** [comment]
i do not see any disadvantages?

**Comment by Schweinepriester** [comment]
me neither, especially by keeping the default after the `added-`
