### ISSUE TITLE
Plugin: missing

### ISSUE THREAD

**Issue by zabelhaft** [Schweinepriester/beets-config#25]
http://beets.readthedocs.io/en/v1.3.19/plugins/missing.html

might be cool as well during import

**Comment by Schweinepriester** [comment]
The plugin 'just' adds a new command `beet missing` and doesn't work during import.

But `beet import` already checks for missing files during import according to the fetched metadata.

Therefore i believe the intended functionality is already present.

Or do you want do use `beet missing`? If not, please close the issue :)
