### ISSUE TITLE
Milestones and general versioning

### ISSUE THREAD

**Issue by Schweinepriester** [Schweinepriester/beets-config#7]
i suggest we follow http://semver.org/ leading to versions like `0.0.1` or `0.0.1-alpha1`

also we will use the git(hub) tagging feature for releases in the future

examples:
- https://github.com/twbs/bootstrap/milestones?state=closed
- https://github.com/twbs/bootstrap/releases

on a sidenote: while its somewhat boring, i recommend reading the semver-stuff, some good thoughts there :)

**Comment by zabelhaft** [comment]
how do i tag?
https://git-scm.com/book/en/v2/Git-Basics-Tagging, but where to add?

**Comment by Schweinepriester** [comment]
while its of cource possible via CLI, i prefer the github-way, in our case: https://github.com/Schweinepriester/beets-config/releases/new, which also creates a new tag

but i think we will und should talk about releasing a version first. then i'm happy to do the rest :)

you already renamed the milestones, thanks!

**Comment by zabelhaft** [comment]
since the export of our string is working, why not release 0.0.1?

**Comment by Schweinepriester** [comment]
did you check the ID3 tags of the imported files? do they contain all information we normally would have? especially "of tracks" and "of CD"?

**Comment by zabelhaft** [comment]
forgot those; can't test until evening...
does beets support these tags?

**Comment by Schweinepriester** [comment]
``` powershell
PS C:\Users\Hollberg> beet fields
Item fields:
  acoustid_fingerprint
  acoustid_id
  added
  album
  album_id
  albumartist
  albumartist_credit
  albumartist_sort
  albumdisambig
  albumstatus
  albumtype
  artist
  artist_credit
  artist_sort
  asin
  bitdepth
  bitrate
  bpm
  catalognum
  channels
  comments
  comp
  composer
  country
  data_source
  day
  disc
  disctitle
  disctotal
  encoder
  filesize
  format
  genre
  grouping
  id
  initial_key
  label
  language
  length
  lyrics
  mb_albumartistid
  mb_albumid
  mb_artistid
  mb_releasegroupid
  mb_trackid
  media
  month
  mtime
  original_day
  original_month
  original_year
  path
  rg_album_gain
  rg_album_peak
  rg_track_gain
  rg_track_peak
  samplerate
  script
  singleton
  title
  track
  tracktotal
  year

Album fields:
  added
  album
  albumartist
  albumartist_credit
  albumartist_sort
  albumdisambig
  albumstatus
  albumtotal
  albumtype
  artpath
  asin
  bitrate
  catalognum
  comp
  country
  data_source
  day
  disctotal
  genre
  id
  label
  language
  mb_albumartistid
  mb_albumid
  mb_releasegroupid
  month
  original_day
  original_month
  original_year
  path
  path
  rg_album_gain
  rg_album_peak
  script
  year
Template fields from plugins:
  bitrate
```

i think so: `tracktotal` and `disctotal`

**Comment by zabelhaft** [comment]
does it write those in auto-tag mode?

**Comment by Schweinepriester** [comment]
``` powershell
PS C:\Users\Hollberg\Desktop> beet ls -f '$tracktotal'
08
08
08
08
08
08
08
08
PS C:\Users\Hollberg\Desktop> beet ls -af '$disctotal'
01
PS C:\Users\Hollberg\Desktop>
```

seems to be the case.

but i'd like to check some files myself in itunes

**Comment by zabelhaft** [comment]
everythin correcly added; close?
